name: Android Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Gradle
        run: |
          # This command searches for gradlew in all folders
          DIR=$(find . -name "gradlew" -printf "%h" | head -n 1)
          cd "$DIR"
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: **/build/outputs/apk/debug/app-debug.apk
