name: Android Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Gradle
        run: |
          # Find the folder containing gradlew and move into it
          PROJECT_DIR=$(find . -name "gradlew" -exec dirname {} \; | head -n 1)
          cd "$PROJECT_DIR"
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: **/build/outputs/apk/debug/app-debug.apk
